language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
before_script:
  - chmod +x manage.py
script:
  - ./manage.py lint
  - coverage run --source exercises ./manage.py test
  - coverage report --fail-under 100
notifications:
  email: false
